name: ai-recruitment-system
type: gradio-space
sdk: streamlit

metadata:
  space_id: Chris4K/ai-recruitment-system
  original_url: https://huggingface.co/spaces/Chris4K/ai-recruitment-system

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 13:45:21
